name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1 # since we cache
  COLOG: 1

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install Verilator
        run: |
          if [[ "$(uname)" == 'Darwin' ]]; then
            brew install verilator
          else
            sudo apt-get install -y verilator
          fi
      - name: Install Swim
        run: cargo install --locked --git https://gitlab.com/spade-lang/swim --rev ed18b1a68a4a4f489868c022577e3de45c1074bf
      - name: Build
        run: swim build
      - name: Test
        run: swim plugin marlin
